# Generated by Django 5.1.7 on 2025-04-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fan',
            old_name='asosiy',
            new_name='assosiy',
        ),
    ]
